{
 "title": "Expé",
 "time": { "from": "2023-08-25T14:58:00.000Z", "to": "2023-08-26T04:58:00.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "${VAR_DATASOURCE}" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\"}, namespace)"
    }
   },
   { "name": "time", "query": "30s, 1m, 5m" },
   { "name": "max_data_points", "label": "Max data points", "query": "1395" },
   { "name": "min_interval", "label": "Min interval", "query": "1m" }
  ]
 },
 "panels": [
  { "title": "k6", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average virtual users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "VUs",
     "query": "SELECT mean(\"value\") FROM \"vus\" WHERE $timeFilter GROUP BY time($time) fill(0)\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "Requests per Second",
     "query": "SELECT sum(\"value\") FROM \"http_reqs\" WHERE $timeFilter GROUP BY time($time) fill(0)"
    }
   ]
  },
  { "title": "Waste", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Wasted CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(1 - rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[$time]))",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"}))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Wasted memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job='node'})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job='node'} - node_memory_MemFree_bytes{job='node'})",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Waste by label", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(1 - rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[$time])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job='node'} - node_memory_MemFree_bytes{job='node'}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Requests ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job='node'}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Waste ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})) by (instance)\n    - \n    sum(1 - rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[$time])) by (instance)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Waste (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(node_memory_MemTotal_bytes{job='node'}) by (instance)\n    - \n    sum(node_memory_MemTotal_bytes{job='node'} - node_memory_MemFree_bytes{job='node'}) by (instance)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Receive Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum by (instance)(\n            irate(node_network_receive_bytes_total{job=\"node\"}[$time])\n        )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum by (instance)(\n            irate(node_network_transmit_bytes_total{job=\"node\"}[$time])\n        )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Rate of received packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum by (instance)(\n            irate(node_network_receive_packets_total{job=\"node\"}[$time])\n        )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum by (instance)(\n            irate(node_network_receive_packets_total{job=\"node\"}[$time])\n        )\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}