{
 "title": "Expé",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Transmit bandwith",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod)(\n            rate(container_network_receive_bytes_total{namespace=\"default\"}[2m])\n        )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transmit bandwith",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod)(\n            rate(container_network_transmit_bytes_total{namespace=\"default\"}[2m])\n        )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"default\", container!=\"\"}\n)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(\n            kube_pod_container_resource_limits{namespace=\"default\", resource=\"memory\"}\n        )",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(\n            kube_pod_container_resource_requests{namespace=\"default\", resource=\"memory\"}\n        )",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_usage_seconds_total{namespace=\"default\", image !=\"\", container!=\"\"}[2m])\n)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{namespace=\"default\", resource=\"cpu\"}\n)",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(\n            kube_pod_container_resource_requests{namespace=\"default\", resource=\"cpu\"}\n        )",
     "legendFormat": "Requests"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Number of pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count by (container) (\n    kube_pod_container_info{namespace=\"default\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Used memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container)(\n            container_memory_working_set_bytes{namespace=\"default\", container!=\"\", image!=\"\"}\n        )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Limits memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container)(\n            kube_pod_container_resource_limits{namespace=\"default\", resource=\"memory\"}\n        )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container)(\n            kube_pod_container_resource_requests{namespace=\"default\", resource=\"memory\"}\n        )",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Used CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (container)(\n            rate(container_cpu_usage_seconds_total{namespace=\"default\", image !=\"\", container!=\"\"}[2m])\n        )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Limits CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by (container)(\n            kube_pod_container_resource_limits{namespace=\"default\", resource=\"cpu\"}\n        )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by (container)(\n            kube_pod_container_resource_requests{namespace=\"default\", resource=\"cpu\"}\n        )",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}