{
 "title": "Experimentation",
 "time": { "from": "2023-08-29T20:12:00.000Z", "to": "2023-08-30T10:12:00.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "Prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info, cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster=~\"$cluster\"}, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   },
   { "name": "time", "query": "15s, 30s, 1m, 5m" }
  ]
 },
 "panels": [
  { "title": "k6", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average virtual users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "VUs",
     "query": "SELECT mean(\"value\") FROM \"vus\" WHERE $timeFilter GROUP BY time($time) fill(0)\n"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "Requests per Second",
     "query": "SELECT sum(\"value\") FROM \"http_reqs\" WHERE $timeFilter GROUP BY time($time) fill(0)"
    }
   ]
  },
  { "title": "Waste", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Wasted CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (\n  irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", cluster=\"$cluster\", image !=\"\"}[$time])\n)",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"default\",resource=\"cpu\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"default\",resource=\"cpu\"})",
     "legendFormat": "Requested"
    }
   ]
  },
  {
   "title": "Wasted memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{namespace=\"$namespace\", cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests{namespace=\"$namespace\", cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\", cluster=~\"$cluster\", node=~\"$node\", pod!=\"\",container!=\"POD\", container!=\"\"})",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Waste by label", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(\n        max(kube_pod_labels{namespace=\"$namespace\"}) by (label_app, pod,label_app_kubernetes_io_name)\n        *\n        on(pod)\n        group_right(label_app,label_app_kubernetes_io_name)\n        sum by (pod)(\n            irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", image !=\"\"}[$time])\n        )\n    ) by(label_app, label_app_kubernetes_io_name)\n)",
     "legendFormat": "{{label_app}}{{label_app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(\n        max(kube_pod_labels{namespace=\"$namespace\"}) by (label_app, pod, label_app_kubernetes_io_name)\n        *\n        on(pod)\n        group_right(label_app, label_app_kubernetes_io_name)\n        sum by (pod)(\n            container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}\n        )\n    ) by(label_app, label_app_kubernetes_io_name)\n)",
     "legendFormat": "{{label_app}}{{label_app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "CPU Requests ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(\n        max(kube_pod_labels{namespace=\"$namespace\"}) by (label_app, pod, label_app_kubernetes_io_name)\n        *\n        on(pod)\n        group_right(label_app, label_app_kubernetes_io_name)\n        sum by (pod)(\n            kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}\n        )\n    ) by(label_app, label_app_kubernetes_io_name)\n)",
     "legendFormat": "{{label_app}}{{label_app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(\n        max(kube_pod_labels{namespace=\"$namespace\"}) by (label_app, pod, label_app_kubernetes_io_name)\n        *\n        on(pod)\n        group_right(label_app, label_app_kubernetes_io_name)\n        sum by (pod)(\n            kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}\n        )\n    ) by(label_app, label_app_kubernetes_io_name)\n)",
     "legendFormat": "{{label_app}}{{label_app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "CPU Waste ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(\n        max(kube_pod_labels{namespace=\"$namespace\"}) by (label_app, pod, label_app_kubernetes_io_name)\n        *\n        on(pod)\n        group_right(label_app, label_app_kubernetes_io_name)\n        sum by (pod)(\n            kube_pod_container_resource_requests{namespace=\"$namespace\", cluster=\"$cluster\", resource=\"cpu\"}\n        )\n    ) by(label_app, label_app_kubernetes_io_name)\n    - \n    sum(\n        max(kube_pod_labels{namespace=\"$namespace\"}) by (label_app, pod, label_app_kubernetes_io_name)\n        *\n        on(pod)\n        group_right(label_app, label_app_kubernetes_io_name)\n        sum by (pod)(\n            irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", cluster=\"$cluster\", image !=\"\"}[$time])\n        )\n    ) by(label_app, label_app_kubernetes_io_name)\n)",
     "legendFormat": "{{label_app}}{{label_app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Memory Waste (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(\n        max(kube_pod_labels{namespace=\"$namespace\"}) by (label_app, pod, label_app_kubernetes_io_name)\n        *\n        on(pod)\n        group_right(label_app, label_app_kubernetes_io_name)\n        sum by (pod)(\n            kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}\n        )\n    ) by(label_app, label_app_kubernetes_io_name)\n    - \n    sum(\n        max(kube_pod_labels{namespace=\"$namespace\"}) by (label_app, pod, label_app_kubernetes_io_name)\n        *\n        on(pod)\n        group_right(label_app, label_app_kubernetes_io_name)\n        sum by (pod)(\n            container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}\n        )\n    ) by(label_app, label_app_kubernetes_io_name)\n)",
     "legendFormat": "{{label_app}}{{label_app_kubernetes_io_name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Receive Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(\n        max(kube_pod_labels{namespace=\"$namespace\"}) by (label_app, pod, label_app_kubernetes_io_name)\n        *\n        on(pod)\n        group_right(label_app, label_app_kubernetes_io_name)\n        sum by (pod)(\n            irate(container_network_receive_bytes_total{namespace=\"$namespace\", cluster=\"$cluster\", image !=\"\"}[$time])\n        )\n    ) by(label_app, label_app_kubernetes_io_name)\n)",
     "legendFormat": "{{label_app}}{{label_app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(\n        max(kube_pod_labels{namespace=\"$namespace\"}) by (label_app, pod, label_app_kubernetes_io_name)\n        *\n        on(pod)\n        group_right(label_app, label_app_kubernetes_io_name)\n        sum by (pod)(\n            irate(container_network_transmit_bytes_total{namespace=\"$namespace\", image !=\"\"}[$time])\n        )\n    ) by(label_app, label_app_kubernetes_io_name)\n)",
     "legendFormat": "{{label_app}}{{label_app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Rate of received packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(\n        max(kube_pod_labels{namespace=\"$namespace\"}) by (label_app, pod, label_app_kubernetes_io_name)\n        *\n        on(pod)\n        group_right(label_app, label_app_kubernetes_io_name)\n        sum by (pod)(\n            irate(container_network_receive_packets_total{namespace=\"$namespace\", image !=\"\"}[$time])\n        )\n    ) by(label_app, label_app_kubernetes_io_name)\n)",
     "legendFormat": "{{label_app}}{{label_app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sort_desc(\n    sum(\n        max(kube_pod_labels{namespace=\"$namespace\"}) by (label_app, pod, label_app_kubernetes_io_name)\n        *\n        on(pod)\n        group_right(label_app, label_app_kubernetes_io_name)\n        sum by (pod)(\n            irate(container_network_receive_packets_total{namespace=\"$namespace\", image !=\"\"}[$time])\n        )\n    ) by(label_app, label_app_kubernetes_io_name)\n)",
     "legendFormat": "{{label_app}}{{label_app_kubernetes_io_name}}"
    }
   ]
  }
 ]
}